In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [4]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [5]:
import numpy as np

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [1]:
pd.__version__

NameError: name 'pd' is not defined

In [24]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__

'3.0.6'

In [4]:
df.index

NameError: name 'df' is not defined

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [6]:
df.index

RangeIndex(start=0, stop=10000, step=1)

In [10]:
df.nunique

<bound method DataFrame.nunique of       model_year  origin fuel_type         drivetrain  num_doors  \
0           2006  Europe  Gasoline  Front-wheel drive          4
1           2008  Europe    Diesel  Front-wheel drive          4
2           1996    Asia  Gasoline  Front-wheel drive          5
3           1989  Europe  Gasoline  Front-wheel drive          4
4           1994     USA    Diesel  Front-wheel drive          3
...          ...     ...       ...                ...        ...
9995        2005     USA  Gasoline    All-wheel drive          4
9996        1993    Asia  Gasoline    All-wheel drive          2
9997        2014     USA  Gasoline    All-wheel drive          3
9998        2004     USA    Hybrid   Rear-wheel drive          5
9999        2011     USA    Diesel  Front-wheel drive          4

      engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                    2180              6       243.0            3870
1                    2390              6       272.0            4210
2                    2320              6       267.0            4240
3                    2130              6       258.0            4490
4                    2580              7       304.0            4510
...                   ...            ...         ...             ...
9995                 2470              6       271.0            4690
9996                 2300              6       244.0            4370
9997                 2480              6       267.0            4590
9998                 2180              6       270.0            4450
9999                 2380              6       295.0            4370

      acceleration  fuel_efficiency_mpg
0              NaN                 31.9
1              NaN                 31.3
2             17.3                 27.5
3             18.7                 28.5
4             17.5                 31.0
...            ...                  ...
9995          18.9                 27.4
9996          19.0                 30.0
9997          18.4                 28.1
9998          20.9                 32.2
9999          17.6                 30.2

[10000 rows x 11 columns]>

In [11]:
df.isnull.sum()

AttributeError: 'function' object has no attribute 'sum'

In [12]:
print(df.columns.tolist())
df.head()

['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors', 'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight', 'acceleration', 'fuel_efficiency_mpg']

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [13]:
len(df)

10000

In [14]:
df["fuel_type"].value_counts()

fuel_type
Gasoline    6913
Diesel      2053
Hybrid      1034
Name: count, dtype: int64

In [15]:
df["fuel_type"].nunique()

3

In [16]:
df.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [17]:
df.isna().any().sum()

np.int64(2)

In [18]:
df["origin"].unique()

<StringArray>
['Europe', 'Asia', 'USA']
Length: 3, dtype: str

In [28]:
df.loc[df["origin"] == "Asia", "fuel_efficiency_mpg"].max()

np.float64(41.2)

In [21]:
median_before = df["horsepower"].median()
most_frequent = df["horsepower"].mode().iloc[0]
horsepower_filled = df["horsepower"].fillna(most_frequent)
median_after = horsepower_filled.median()
print("Медиана до:", median_before)
print("Самое частое значение:", most_frequent)
print("Медиана после:", median_after)
if median_after > median_before:
    print("Yes, it increased")
elif median_after < median_before:
    print("Yes, it decreased")
else:
    print("No")

Медиана до: 254.0
Самое частое значение: 252.0
Медиана после: 252.0
Yes, it decreased

In [27]:
X = (
    df.loc[df["origin"] == "Asia", ["vehicle_weight", "model_year"]]
    .head(7)
    .to_numpy(dtype=float)
)

XTX = X.T @ X
XTX_inv = np.linalg.inv(XTX)
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
w = XTX_inv @ X.T @ y

print("Веса:", w)
print("Сумма весов:", w.sum())
print("С округлением:", round(w.sum(), 4))

Веса: [0.13644777 0.2327492 ]
Сумма весов: 0.36919696904925486
С округлением: 0.3692